// Temporary shims for Convex React until the package is installed and initialized.
declare module "convex/react" {
  export class ConvexReactClient {
    constructor(url: string);
  }
  export const ConvexProvider: any;
  export function useQuery(fn: any, args?: any): any;
  export function useMutation(fn: any): any;
}

declare module "convex/_generated/api" {
  // Minimal shape; real types will be generated by Convex.
  export const api: any;
}
